language: node_js
node_js:
  - "8"
cache: yarn
addons:
  apt:
    packages:
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test
env:
  CXX=g++-4.8
branches:
  only:
    - master
before_script:
  - "yarn global add codecov"
script:
  - "yarn lint"
  - "yarn test"
  - "yarn test:cov"
  - "yarn build"
after_success:
  - "codecov --token=${CODECOV_UPLOAD_TOKEN}"
  # - "yarn docs:publish"
  # - "firebase deploy --token=${FIREBASE_API_TOKEN}"
